WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT    = _{ !"\\" ~ "#" ~ (!NEWLINE ~ ANY)+ ~ NEWLINE? }

// Prelude options

backup_ext               = { "backup_ext" ~ "=" ~ expr }
template                 = { "template" ~ "=" ~ expr }
delimiter                = { "delimiter" ~ "=" ~ expr }
file                     = { "file" ~ "=" ~ expr }
files                    = { "files" ~ "=" ~ expr }
pipe_in                  = { "pipe_in" ~ "=" ~ expr }
pipe_out                 = { "pipe_out" ~ "=" ~ expr }
write                    = { "write" ~ "=" ~ expr }
max_jobs                 = { "max_jobs" ~ "=" ~ expr }
trace                    = { "trace" }
json                     = { "json" }
linewise                 = { "linewise" }
serial                   = { "serial" }
trim_fields              = { "trim_fields" }
keep_mode                = { "keep_mode" }
backup                   = { "backup" }
edit_inplace             = { "edit_inplace" }
silent                   = { "silent" }
no_input                 = { "no_input" }
global_uses_line_numbers = { "global_uses_line_numbers" }

opt    = {
    json
  | pipe_in
  | pipe_out
  | linewise
  | serial
  | trim_fields
  | keep_mode
  | backup_ext
  | backup
  | template
  | delimiter
  | max_jobs
  | trace
  | file
  | no_input
  | silent
  | global_uses_line_numbers
  | edit_inplace
  | write
  | files
}
opts = { "opt" ~ "{" ~ ((opt ~ ",")* ~ opt?)? ~ "}" }

// Script Commands
// Whitespace positioning needs to be enforced strictly here

global        = ${ ("global" | "g") ~ " "+ ~ expr ~ WHITESPACE* ~ block ~ WHITESPACE* }
not_global    = ${ ("v" | "not_global" | "!global") ~ " "+ ~ expr ~ WHITESPACE* ~ block ~ WHITESPACE* }
move          = ${ ("move" | "m") ~ " "+ ~ expr ~ WHITESPACE* }
cut           = ${ ("cut" | "c") ~ " "+ ~ expr ~ WHITESPACE* }
next          = ${ "next" | "n" ~ WHITESPACE* }
echo          = ${ ("echo") ~ (" "+ ~ expr)* }
repeat        = ${ ("repeat" | "r") ~ " "+ ~ expr ~ " "+ ~ block }
yank          = ${ ("yank" | "y") ~ " "+ ~ expr ~ " "+ ~ expr ~ WHITESPACE* }
break_loop    = ${ ("break") ~ WHITESPACE* }
shell_cmd     = ${ ("command" | "cmd") ~ " "+ ~ expr ~ WHITESPACE* }
push          = ${ ("push") ~ " "+ ~ expr ~ " "+ ~ expr ~ WHITESPACE* }
pop           = ${ ("pop") ~ " "+ ~ expr ~ WHITESPACE* }
buf_cmd       = ${ "buf" ~ " "+ ~ buf_cmd_arg ~ WHITESPACE* }
buf_cmd_arg   = ${ (buf_switch ~ WHITESPACE+ ~ expr) | buf_id }
buf_switch    = ${ "switch" }
buf_id        = ${ "id" }
continue_loop = ${ ("continue") ~ WHITESPACE* }
return        = ${ ("return" | "ret") ~ " "+ ~ expr ~ WHITESPACE* }
include       = ${ ("include") ~ " "+ ~ expr ~ WHITESPACE* }

command = {
    global
  | not_global
  | move
  | cut
  | next
  | echo
  | repeat
  | yank
  | break_loop
  | shell_cmd
  | push
  | pop
  | buf_cmd
  | continue_loop
  | return
  | include
}

// Control Flow

range           = { expr ~ ".." ~ expr }
range_inclusive = { expr ~ "..=" ~ expr }

for_block          = { "for" ~ var ~ "in" ~ (range_inclusive | range | expr) ~ block }
while_block        = { "while" ~ expr_bool_priority ~ block }
until_block        = { "until" ~ expr_bool_priority ~ block }
if_block           = { "if" ~ expr_bool_priority ~ block ~ elif_block* ~ else_block? }
elif_block         = { "elif" ~ expr_bool_priority ~ block }
else_block         = { "else" ~ block }
expr_bool_priority = { bool_expr | expr }

// Expressions
// We will just allow indexes on these
// And check at run time if it's a valid spot for one
bin_expr = { bin_atom ~ (bin_op ~ bin_atom)+ }
bin_atom = { bin_lit | ("(" ~ bin_expr ~ ")") }
bin_lit  = { negative? ~ expr_not_recursive }
bin_op   = { add | sub | mult | div | modulo | pow }
add      = { "+" }
sub      = { "-" }
mult     = { "*" }
div      = { "/" }
modulo   = { "%" }
pow      = { "**" }
negative = { "-" }

bool_expr = { bool_atom ~ (bool_op ~ bool_atom)+ }
bool_atom = { bool_lit | ("(" ~ bool_expr ~ ")") }
bool_lit  = { not? ~ (expr_not_recursive | ("(" ~ bin_expr ~ ")")) }

bool_op = { eq | ne | lt | le | ge | gt | and | or }
eq      = { "==" }
ne      = { "!=" }
lt      = { "<" }
le      = { "<=" }
gt      = { ">" }
ge      = { ">=" }
and     = { "&&" }
or      = { "||" }
not     = { "!" }

// I'm not sure why I need to nest these rules like this
// but it didn't work right until I did
expr               = {
    (func_call | (bool_expr | bin_expr | (command | value))) ~ index*
}
expr_not_recursive = {
    (command | func_call | value) ~ index*
}

index        = {
    "[" ~ (index_to | index_to_inc | slice | slice_inc | index_from | index_sng) ~ "]"
}
index_to     = { ".." ~ expr }
index_to_inc = { "..=" ~ expr }
slice        = { expr ~ ".." ~ expr }
slice_inc    = { expr ~ "..=" ~ expr }
index_from   = { expr ~ ".." }
index_sng    = { expr }

// Variable Operations
var         = @{ (ASCII_ALPHANUMERIC | "_")+ }
var_declare =  { "let" ~ var ~ "=" ~ expr }
var_mut     =  { var ~ "=" ~ expr }
var_add     =  { var ~ "+=" ~ expr }
var_sub     =  { var ~ "-=" ~ expr }
var_mult    =  { var ~ "*=" ~ expr }
var_div     =  { var ~ "/=" ~ expr }
var_pow     =  { var ~ "^=" ~ expr }
var_mod     =  { var ~ "%=" ~ expr }

// Function stuff

var_list = { (var ~ ",")* ~ var? }

closure_def_args = { "|" ~ var_list ~ "|" }

func_def_args = { "(" ~ var_list ~ ")" }
func_name     = { var ~ func_def_args }
func_def      = { "def" ~ func_name ~ block }

func_call_args = { "(" ~ expr_list ~ ")" }
func_call      = { var ~ func_call_args }

// Primitives

str_inner     = ${ ("\\\\" | ("\\" ~ "\"") | (!"\"" ~ ANY))* }
raw_inner     =  ${ (!PEEK_ALL ~ ANY)* }
str_literal   =  ${ raw_literal | ("\"" ~ str_inner ~ "\"") }
raw_literal   =  _{ "r" ~ PUSH("-") ~ (&PEEK ~ PUSH("-"))* ~ PUSH("\"") ~ raw_inner ~ POP_ALL }
closure       =  { closure_def_args ~ block }

true  = { "true" }
false = { "false" }
bool  = { true | false }

int = @{ ASCII_DIGIT+ }

array = { "[" ~ expr_list ~ "]" }

expr_list = { ((expr ~ ",")* ~ expr?)? }

null = { "null" }

regex_delim = _{ !(ASCII_ALPHANUMERIC | "'" | "}" | "{" | "(" | ")" | "[" | "]") ~ ANY }
regex       =  { PUSH(regex_delim) ~ (&PEEK ~ PUSH(regex_delim))* ~ raw_inner ~ POP_ALL }

register = { "@" ~ reg_name }
reg_name = { ASCII_ALPHA }

value = {
    array
  | null
  | int
  | str_literal
  | var
  | closure
  | bool
  | register
  | regex
}

top_level_cmd = {
    var_declare
  | opts
  | var_add
  | var_sub
  | var_mut
  | var_mult
  | var_div
  | var_pow
  | var_mod
  | for_block
  | if_block
  | while_block
  | until_block
  | command
  | func_def
  | func_call
}

block = !{ "{" ~ top_level_cmd* ~ "}" }

vic = { SOI ~ WHITESPACE* ~ top_level_cmd* ~ WHITESPACE* ~ EOI }
