name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup toolchain
        run: |
          rustup override set nightly
          rustup target add x86_64-unknown-linux-musl

      - name: Run tests
        run: cargo test --release

      - name: Install musl tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build dynamic binary
        run: |
          cargo build --release
          cp target/release/vicut vicut-x86_64-linux-dynamic

      - name: Build static binary
        env:
          RUSTFLAGS: '-C relocation-model=static'
          CC: musl-gcc
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/vicut vicut-x86_64-linux-static

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vicut-x86_64-linux-dynamic
            vicut-x86_64-linux-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
